#!/usr/bin/env bash
# inventory-skills.sh -- Generate docs/inventory.md with count of skills per source.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_MD="${1:-$REPO_ROOT/docs/inventory.md}"

CLAUDE_SKILLS="${CLAUDE_SKILLS_DIR:-$HOME/.claude/skills}"
PI_SKILLS="${PI_SKILLS_DIR:-$HOME/.pi/agent/skills}"
OPENCODE_CMDS="${OPENCODE_COMMANDS_DIR:-$HOME/.config/opencode/commands}"
SHARED_SKILLS="${SHARED_SKILLS_DIR:-$HOME/Dev/shared-skills}"
VOICE_SKILLS="${VOICE_SKILLS_DIR:-$HOME/Dev/voice-skills}"  # e.g. an openjarvis checkout

# Count function
count_dirs() {
	local dir="$1"
	if [[ -d "$dir" ]]; then
		find "$dir" -maxdepth 1 -type d | wc -l
	else
		echo "0"
	fi
}

cat >"$OUTPUT_MD" <<EOF
## Skills Inventory ($(date -u +%Y-%m-%d))

*Generated by \`scripts/inventory-skills.sh\`. Paths are depersonalized.*

| Source | Root (env) | Count |
| ------ | ---------- | ----- |
| Claude skills | \`$CLAUDE_SKILLS\` | $(count_dirs "$CLAUDE_SKILLS") |
| pi user skills | \`$PI_SKILLS\` | $(count_dirs "$PI_SKILLS") |
| OpenCode commands | \`$OPENCODE_CMDS\` | $(count_dirs "$OPENCODE_CMDS" || echo "N/A") *.md files
| Shared/generic skills | \`$SHARED_SKILLS\` | $(count_dirs "$SHARED_SKILLS") |
| Voice skills | \`$VOICE_SKILLS\` | $(count_dirs "$VOICE_SKILLS") |

## Key Source Paths (from plan.md appendix)

The \`plan.md\` Known Skill Paths Appendix lists every directory with its full path.
Use that appendix to avoid rediscovering skills during inventory.

EOF

echo "Wrote $OUTPUT_MD"
